In [1]:
#work in progress

import numpy as np
import pandas as pd
from sklearn.linear_model import SGDClassifier  #uses Stochastic Gradient DEscent for training for classification tasks
from sklearn.preprocessing import StandardScaler #for scaling or normalizing data
from sklearn.model_selection import train_test_split  #splits dataset into training and testing sets
from sklearn.metrics import accuracy_score #metric to evaluate performance by comparing predicted values (y_pred) and true values (y_test)

In [2]:
## reads data
# import seaborn as sns
# penguins = sns.load_dataset("penguins")
# print(type(penguins))
# reads csv-file
penguins = pd.read_csv("penguins.csv")
# Anzeigen der ersten 5 Zeilen
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [3]:
### deletes empty rows ### 
print(penguins.loc[penguins["bill_length_mm"].isnull()])       # checks if there are missing values (NaN) in bill_lenght_mm and prints them
print(penguins.loc[penguins["bill_length_mm"].isnull()].index) # line index
penguins.drop(index = penguins.loc[penguins["bill_length_mm"].isnull()].index, inplace = True) # deletes those rows
penguins.iloc[[160]]

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
3    Adelie  Torgersen             NaN            NaN                NaN   
339  Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g  sex  
3            NaN  NaN  
339          NaN  NaN  
Index([3, 339], dtype='int64')


species island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
161  Chinstrap  Dream            51.3           19.9              198.0   

     body_mass_g   sex  
161       3700.0  MALE

In [4]:
### numpy arrays für for X and y ###
species = penguins['species']
y = np.array(species)
values = penguins[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]
X = np.array(values)
print(X)

[[  39.1   18.7  181.  3750. ]
 [  39.5   17.4  186.  3800. ]
 [  40.3   18.   195.  3250. ]
 ...
 [  50.4   15.7  222.  5750. ]
 [  45.2   14.8  212.  5200. ]
 [  49.9   16.1  213.  5400. ]]


In [5]:
### scaling data so that all have zero mean and unit variance###
scaler = StandardScaler() #initializes StandardScaler object
X = scaler.fit_transform(X) #applies scaling (standardizes data) to X
print(type(X))
print(X)

<class 'numpy.ndarray'>
[[-0.88449874  0.78544923 -1.41834665 -0.56414208]
 [-0.81112573  0.1261879  -1.06225022 -0.50170305]
 [-0.66437972  0.43046236 -0.42127665 -1.18853234]
 ...
 [ 1.18828874 -0.73592307  1.50164406  1.93341896]
 [ 0.23443963 -1.19233476  0.7894512   1.24658968]
 [ 1.09657248 -0.53307343  0.86067049  1.49634578]]


In [6]:
### splitting into training and testing data ###
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #0.2 -> 20% for testing data, 80 for training, 42 -> rng seed to see if split reproducible
print(X_train)

[[-0.22414167  0.58259959 -0.35005737 -0.15828841]
 [-1.80166135  0.48117477 -0.56371522 -0.90755672]
 [-1.26970704 -0.33022379 -1.13346951 -1.00121526]
 ...
 [-1.04958801  1.44471056 -0.77737308 -0.376825  ]
 [ 0.83976695 -1.54732163  1.35920549  1.37146773]
 [-1.12296102  1.44471056 -0.77737308  0.06024818]]


In [7]:
### scikit-learn classifier initialize and training ###
clf = SGDClassifier(loss='hinge', random_state=42) 
clf.fit(X_train, y_train) #trains model clf using X and y train

SGDClassifier(random_state=42)

In [8]:
### predictions on test data ###
y_pred = clf.predict(X_test) #y_pred will includ predicitons on test data X_test)

In [9]:
### test results ###
accuracy = accuracy_score(y_test, y_pred) #compares true with test and calculates accuracy
print("Accuracy:", accuracy)

Accuracy: 0.9855072463768116


In [10]:
### testing specific data points ###
Xn = np.array([[50.4,   15.7,  222.,  5750.]]) #  testing (341, Gentoo)
Xn = np.array([[39.1,   18.7,  181.,  3750.]]) #  testing (0, Adelie)
Xn = np.array([[51.3, 19.9, 198.0, 3700.0]])   #  testing (0, Chinstrap)
Xn = scaler.transform(Xn)                      # new data points are scaled to match training data
print(Xn)
y_pred = clf.predict(Xn) #predicts species for the data points in Xn
print(y_pred)

[[ 1.35337801  1.39399815 -0.20761879 -0.6265811 ]]
['Chinstrap']
